Entity/Reporte.php
<?php

namespace AscensoDigital\PerfilBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Reporte
 *
 * @ORM\Table(name="ad_perfil_reporte")
 * @ORM\Entity(repositoryClass="AscensoDigital\PerfilBundle\Repository\ReporteRepository")
 */
class Reporte
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\SequenceGenerator(sequenceName="reporte_id_seq", allocationSize=1, initialValue=1)
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=200, nullable=false)
     */
    protected $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="codigo", type="string", length=30, nullable=false, unique=true)
     */
    protected $codigo;

    /**
     * @var string
     *
     * @ORM\Column(name="descripcion", type="text", nullable=true)
     */
    protected $descripcion;

    /**
     * @var string
     *
     * @ORM\Column(name="route", type="string", length=100, nullable=true)
     */
    protected $route;

    /**
     * @var integer
     *
     * @ORM\Column(name="orden", type="integer", nullable=true)
     */
    protected $orden;

    /**
     * @var string
     *
     * @ORM\Column(name="manager", type="string", length=50, nullable=true)
     */
    protected $manager;

    /**
     * @var string
     *
     * @ORM\Column(name="repositorio", type="string", length=100, nullable=true)
     */
    protected $repositorio;

    /**
     * @var string
     *
     * @ORM\Column(name="metodo", type="string", length=100, nullable=true)
     */
    protected $metodo;

    /**
     * @var string
     * @ORM\Column(name="sql", type="text", nullable=true)
     */
    protected $sql;

    /**
     * @var boolean
     *
     * @ORM\Column(name="show_proveedor", type="boolean", nullable=true)
     */
    protected $showProveedor = false;

    /**
     * @var Permiso
     *
     * @ORM\ManyToOne(targetEntity="Permiso")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="permiso_id", referencedColumnName="id")
     * })
     */
    protected $permiso;

    /**
     * @var ReporteSeccion
     *
     * @ORM\ManyToOne(targetEntity="ReporteSeccion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="reporte_seccion_id", referencedColumnName="id")
     * })
     */
    protected $reporteSeccion;

    /**
     * @var ReporteCategoria
     *
     * @ORM\ManyToOne(targetEntity="ReporteCategoria")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="reporte_categoria_id", referencedColumnName="id")
     * })
     */
    protected $reporteCategoria;

    /**
     * @var ReporteCriterio
     *
     * @ORM\ManyToOne(targetEntity="ReporteCriterio")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="reporte_criterio_id", referencedColumnName="id")
     * })
     */
    protected $reporteCriterio;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="ReporteXCriterio", mappedBy="reporte", cascade={"persist"} )
     */
    protected $reporteXCriterios;



    public function __construct() {
        $this->reporteXCriterios = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getNombre();
    }

    public function getNombreReporte($show_nombre){
        return $this->getCodigo().(1==$show_nombre ? '-'.$this->getNombre() : '');
    }

    /**
     * @param $criterio_valor
     * @return ReporteXCriterio|null
     */
    public function getReporteEstatico($criterio_valor) {
        if(0==$this->getReporteXCriterios()->count()){
            return null;
        }
        /** @var ReporteXCriterio $rxp */
        foreach ($this->getReporteXCriterios()->getValues() as $rxp) {
            if($rxp->getCriterioId()==$criterio_valor){
                return $rxp;
            }
        }
        return null;
    }

    public function hasCriterio() {
        return !is_null($this->getReporteCriterio());
    }

    public function isExternalUrl() {
        return substr_count($this->getRoute(),"http")>0;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $nombre
     * @return Reporte
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
        return $this;
    }

    /**
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * @param string $codigo
     * @return Reporte
     */
    public function setCodigo($codigo)
    {
        $this->codigo = $codigo;
        return $this;
    }

    /**
     * @return string
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * @param string $descripcion
     * @return Reporte
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * @param string $route
     * @return Reporte
     */
    public function setRoute($route)
    {
        $this->route = $route;
        return $this;
    }

    /**
     * @return string
     */
    public function getRoute()
    {
        return $this->route;
    }

    /**
     * @param Permiso $permiso
     * @return Reporte
     */
    public function setPermiso($permiso)
    {
        $this->permiso = $permiso;
        return $this;
    }

    /**
     * @return Permiso
     */
    public function getPermiso()
    {
        return $this->permiso;
    }

    /**
     * @param ReporteSeccion $reporteSeccion
     * @return Reporte
     */
    public function setReporteSeccion($reporteSeccion)
    {
        $this->reporteSeccion = $reporteSeccion;
        return $this;
    }

    /**
     * @return ReporteSeccion
     */
    public function getReporteSeccion()
    {
        return $this->reporteSeccion;
    }

    /**
     * @param ReporteCategoria $reporteCategoria
     * @return Reporte
     */
    public function setReporteCategoria($reporteCategoria)
    {
        $this->reporteCategoria = $reporteCategoria;
        return $this;
    }

    /**
     * @return ReporteCategoria
     */
    public function getReporteCategoria()
    {
        return $this->reporteCategoria;
    }

    /**
     * @param ReporteCriterio $reporteCriterio
     * @return Reporte
     */
    public function setReporteCriterio($reporteCriterio)
    {
        $this->reporteCriterio = $reporteCriterio;
        return $this;
    }

    /**
     * @return ReporteCriterio
     */
    public function getReporteCriterio()
    {
        return $this->reporteCriterio;
    }

    /**
     * @param int $orden
     * @return Reporte
     */
    public function setOrden($orden)
    {
        $this->orden = $orden;
        return $this;
    }

    /**
     * @return int
     */
    public function getOrden()
    {
        return $this->orden;
    }

    /**
     * @param \Doctrine\Common\Collections\Collection $reporteXCriterios
     * @return Reporte
     */
    public function setReporteXCriterios($reporteXCriterios)
    {
        $this->reporteXCriterios = $reporteXCriterios;
        return $this;
    }

    /**
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getReporteXCriterios()
    {
        return $this->reporteXCriterios;
    }

    /**
     * @param string $repositorio
     * @return Reporte
     */
    public function setRepositorio($repositorio)
    {
        $this->repositorio = $repositorio;
        return $this;
    }

    /**
     * @return string
     */
    public function getRepositorio()
    {
        return $this->repositorio;
    }

    /**
     * @param string $metodo
     * @return Reporte
     */
    public function setMetodo($metodo)
    {
        $this->metodo = $metodo;
        return $this;
    }

    /**
     * @return string
     */
    public function getMetodo()
    {
        return $this->metodo;
    }

    /**
     * @param string $manager
     * @return Reporte
     */
    public function setManager($manager)
    {
        $this->manager = $manager;
        return $this;
    }

    /**
     * @return string
     */
    public function getManager()
    {
        return $this->manager;
    }

    /**
     * @param boolean $showProveedor
     * @return Reporte
     */
    public function setShowProveedor($showProveedor)
    {
        $this->showProveedor = $showProveedor;
        return $this;
    }

    /**
     * @return boolean
     */
    public function isShowProveedor()
    {
        return $this->showProveedor;
    }

    /**
     * @param string $sql
     * @return Reporte
     */
    public function setSql($sql)
    {
        $this->sql = $sql;
        return $this;
    }

    /**
     * @return string
     */
    public function getSql()
    {
        return $this->sql;
    }

}

Resources/views/Reporte/index.html.twig
{% extends 'ADPerfilBundle::layout.html.twig' %}

{% block ad_perfil_title %}Reportes{% endblock ad_perfil_title %}

{% block ad_perfil_content %}
    {{ include('ADPerfilBundle:Reporte:index_content.html.twig') }}
{% endblock ad_perfil_content %}

{% block ad_perfil_javascripts %}
    {{ parent() }}
    {% javascripts
    'bundles/adperfil/js/ad_perfil.reporte.js' filter='?yui_js' output='js/compiled/reporte.js' %}
    <script src="{{ asset_url }}" type="text/javascript"></script>
    {% endjavascripts %}
{% endblock %}

Resources/views/Reporte/index_content.html.twig
{{ render(controller('ADPerfilBundle:Navegacion:breadcrumbs')) }}
{{ render(controller('ADPerfilBundle:Navegacion:menu')) }}
{{ render(controller('ADPerfilBundle:Navegacion:pageTitle')) }}

{% for seccion, categorias in data.reportes %}
    <div class="panel panel-{{ categorias.style }}">
        <div class="panel-heading"><h4>{{ seccion | title }}</h4></div>
        <div class="panel-body">
        {% for categoria, reportes in categorias.reportes %}
            <fieldset>
                <legend>{{ categoria | title }}</legend>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="col-md-1">N°</th>
                        <th class="col-md-2">Código</th>
                        <th class="col-md-3">Nombre</th>
                        <th class="col-md-5">Descripción</th>
                        <th class="col-md-1"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rp in reportes %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ rp.codigo }}</td>
                        <td>{{ rp.nombre }}</td>
                        <td>{{ rp.descripcion }}</td>
                        <td>
                            {% set route= rp.route is not null ? rp.route : 'ad_perfil_reporte' %}
                            <a href="{{ rp.hasCriterio ? '#modal' ~ rp.reporteCriterio | capitalize : path(route, {'reporte_id' : rp.codigo}) }}" {% if rp.hasCriterio %}data-url="{{ path(route, {'reporte_id' : rp.codigo}) }}" data-toggle="modal" data-reporte="{{ rp.nombre }}"{% endif %}><i class="fa fa-cloud-download"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </fieldset>
        {% endfor %}
        </div>
    </div>
{% else %}
    <div class="alert alert-warning">No tienes reportes disponibles</div>
{% endfor %}

{% for nombre,criterio in data.criterios %}
<div class="modal fade" id="modal{{ nombre | capitalize }}" tabindex="-1" role="dialog" aria-labelledby="modalLabel{{ nombre | capitalize }}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalLabel{{ nombre | capitalize }}">{{ criterio.title }}</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-info">Seleccione el {{ criterio.title }} para el reporte <span id="rep-nombre"></span></div>
                <ul class="list-group">
                    {% for i in criterio.data %}
                        <li class="list-group-item"><a class="modal-link" data-valor="{{ i.id }}">{{ i }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endfor %}

Resources/views/Reporte/list.html.twig
{% extends '@ADPerfilBundle/layout.html.twig' %}

{% block ad_perfil_title %}Reportes{% endblock ad_perfil_title %}

{% block ad_perfil_content %}
    {{ include('@ADPerfilBundle/Reporte/list_content.html.twig') }}
{% endblock ad_perfil_content %}

{% block ad_perfil_javascripts %}
    {{ parent() }}
    {% javascripts
    'bundles/adperfil/js/ad_perfil.reporte.js' filter='?jsqueeze' output='js/compiled/reporte.js' %}
    <script src="{{ asset_url }}" type="text/javascript"></script>
    {% endjavascripts %}
{% endblock %}

Resources/views/Reporte/list_content.html.twig
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::breadcrumbsAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::menuAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::pageTitleAction')) }}

{% set fecha= '?v=' ~ ("now" | date('YmdHis')) %}
{% for seccion, categorias in data.reportes %}
    <div class="panel panel-{{ categorias.style }}">
        <div class="panel-heading"><h4>{{ seccion | title }}</h4></div>
        <div class="panel-body">
        {% for categoria, reportes in categorias.categorias %}
            <fieldset>
                <legend>{% if not reportes.icono is null %}<i class="{{ reportes.icono }}"></i> {% endif %}{{ categoria | title }}</legend>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="col-md-1">N°</th>
                        <th class="col-md-2">Código</th>
                        <th class="col-md-3">Nombre</th>
                        <th class="col-md-5">Descripción</th>
                        <th class="col-md-1"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rp in reportes.reportes %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ rp.codigo }}</td>
                        <td>{{ rp.nombre }}</td>
                        <td>{{ rp.descripcion }}</td>
                        <td>
                            {% if rp.externalUrl %}
                                <a href="{{ rp.route }}" title="Descargar" target="_blank"><i class="fa fa-fw fa-cloud-download"></i></a>
                            {% else %}
                                {% set route= rp.route is not null ? rp.route : 'ad_perfil_reporte' %}
                                <a href="{{ rp.hasCriterio ? '#modal' ~ rp.reporteCriterio | capitalize : path(route, {'reporte_id' : rp.codigo, 'show_nombre' : 0}) ~ fecha }}" {% if rp.hasCriterio %}data-url="{{ path(route, {'reporte_id' : rp.codigo, 'show_nombre' : 0}) }}" data-toggle="modal" data-reporte="{{ rp.nombre }}"{% endif %} title="Descargar"><i class="fa fa-fw fa-cloud-download"></i></a>
                                {% if downloadNombre %}
                                    <a href="{{ rp.hasCriterio ? '#modal' ~ rp.reporteCriterio | capitalize : path(route, {'reporte_id' : rp.codigo, 'show_nombre' : 1}) ~ fecha }}" {% if rp.hasCriterio %}data-url="{{ path(route, {'reporte_id' : rp.codigo, 'show_nombre' : 1}) }}" data-toggle="modal" data-reporte="{{ rp.nombre }}"{% endif %} title="Descargar con Nombre"><i class="fa fa-fw fa-info-circle"></i></a>
                                {% endif %}
                            {% endif %}
                            {% if canEdit %}
                                &nbsp;<a href="{{ path('ad_perfil_reporte_edit', { 'codigo' : rp.codigo }) }}" title="Editar Reporte"><i class="fa fa-fw fa-pencil-square-o"></i></a>
                            {% endif %}
                            {% if canLoad %}
                                &nbsp;<a href="{{ path('ad_perfil_reporte_load_estatico', { 'codigo' : rp.codigo }) }}" title="Cargar Estático"><i class="fa fa-fw fa-link"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </fieldset>
        {% endfor %}
        </div>
    </div>
{% else %}
    <div class="alert alert-warning">No tienes reportes disponibles</div>
{% endfor %}

{% for nombre,criterio in data.criterios %}
<div class="modal fade" id="modal{{ nombre | capitalize }}" tabindex="-1" role="dialog" aria-labelledby="modalLabel{{ nombre | capitalize }}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalLabel{{ nombre | capitalize }}">Seleccione {{ criterio.titulo }} para "<span id="modal{{ nombre | capitalize }}_rep_nombre"></span>"</h4>
            </div>
            <div class="modal-body">
                <ul class="list-group">
                    {% for i in criterio.data %}
                        <li class="list-group-item"><a class="modal-link" data-valor="{{ i.id }}">{{ i }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endfor %}

Resources/views/Reporte/load-estatico.html.twig
{% extends '@ADPerfilBundle/layout.html.twig' %}

{% block ad_perfil_title %}Reportes{% endblock ad_perfil_title %}
{% block ad_perfil_subtitle %}Cargar Reporte Estatico{% endblock ad_perfil_subtitle %}

{% block ad_perfil_content %}
    {{ include('@ADPerfilBundle/Reporte/load-estatico_content.html.twig') }}
{% endblock ad_perfil_content %}

Resources/views/Reporte/load-estatico_content.html.twig
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::breadcrumbsAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::menuAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::pageTitleAction')) }}

{{ form_start(form) }}
<div class="panel panel-default">
    <div class="panel-body">
        {{ form_widget(form) }}
    </div>
    <div class="panel-footer text-right">
        <button class="btn btn-primary" type="submit">Cargar</button>&nbsp;
        <a class="btn btn-danger" href="{{ path('ad_perfil_menu', {'menu_slug' : 'reportes'}) }}">Cancelar</a>
    </div>
</div>
{{ form_end(form) }}

Resources/views/Reporte/new.html.twig
{% extends '@ADPerfilBundle/layout.html.twig' %}

{% block ad_perfil_title %}Reportes{% endblock ad_perfil_title %}
{% block ad_perfil_subtitle %}Crear Reporte{% endblock ad_perfil_subtitle %}
{% block ad_perfil_content %}
    {{ include('@ADPerfilBundle/Reporte/new_content.html.twig') }}
{% endblock ad_perfil_content %}

Resources/views/Reporte/new_content.html.twig
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::breadcrumbsAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::menuAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::pageTitleAction')) }}

{{ form_start(form) }}
<div class="panel panel-default">
    <div class="panel-body">
        {{ form_widget(form) }}
    </div>
    <div class="panel-footer text-right">
        <button class="btn btn-primary" type="submit">Crear</button>&nbsp;
        <a class="btn btn-danger" href="{{ path('ad_perfil_menu', {'menu_slug' : 'reportes'}) }}">Cancelar</a>
    </div>
</div>
{{ form_end(form) }}

Resources/views/Reporte/reporte.csv.twig
sep=;
{% set encabezado=true %}
{% for fila in data %}
{% if encabezado %}
{% set encabezado=false %}
{% if proveedor_id > 0 %}IdProveedor;{% endif %}{% for key in fila | keys %}{% if not loop.first %};{% endif %}{{ '"' ~ (key | replace({'_' : ' '}) | title | replace({' ' : separador}) ) ~ '"' }}{% endfor %}{% if proveedor_id > 0 %};vnumregistro{% endif %}

{% endif %}
{% if proveedor_id > 0 %}{{ proveedor_id }};{% endif %}{% for dat in fila %}{% if not loop.first %};{% endif %}{{ '"' ~ (dat is null ? 0 : (dat is same as(true) ? ad_perfil_get_config('valor_true') : ( dat is same as(false) ? ad_perfil_get_config('valor_false') : ( dat | is_numeric ? dat | replace({'.': ','}) : dat | raw) ))) ~ '"' }}{%  endfor %}{% if proveedor_id > 0 %};{{ loop.index }}{% endif %}

{% endfor %}