Entity/Perfil.php
<?php
/**
 * Created by PhpStorm.
 * User: claudio
 * Date: 20-01-16
 * Time: 13:43
 */

namespace AscensoDigital\PerfilBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

abstract class Perfil
{
    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="AscensoDigital\PerfilBundle\Entity\PerfilXPermiso", mappedBy="perfil", cascade={"persist"} )
     */
    protected $perfilXPermisos;

    public abstract function getNombre();
    
    public function __construct() {
        $this->perfilXPermisos = new ArrayCollection();
    }

    public function loadPermisos($ps) {
        /** @var Permiso $p */
        foreach($ps as $p) {
            $encontrado=false;
            foreach($this->getPerfilXPermisos() as $pxp) {
                if($pxp->getPermiso()->getId()==$p->getId()){
                    $encontrado=true;
                    break;
                }
            }
            if(!$encontrado) {
                $pxpn=new PerfilXPermiso();
                $pxpn->setPermiso($p)
                    ->setPerfil($this);
                $this->addPerfilXPermiso($pxpn);
            }
        }
    }

    /**
     * Add perfilXPermisos
     *
     * @param PerfilXPermiso $perfilXPermisos
     * @return Perfil
     */
    public function addPerfilXPermiso(PerfilXPermiso $perfilXPermisos)
    {
        $this->perfilXPermisos[] = $perfilXPermisos;

        return $this;
    }

    /**
     * Remove perfilXPermisos
     *
     * @param PerfilXPermiso $perfilXPermisos
     */
    public function removePerfilXPermiso(PerfilXPermiso $perfilXPermisos)
    {
        $this->perfilXPermisos->removeElement($perfilXPermisos);
    }

    /**
     * Get perfilXPermisos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPerfilXPermisos()
    {
        return $this->perfilXPermisos;
    }
}

Controller/NavegacionController.php
<?php

namespace AscensoDigital\PerfilBundle\Controller;

use AscensoDigital\PerfilBundle\Entity\Menu;
use AscensoDigital\PerfilBundle\Form\Type\MenuFormType;
use AscensoDigital\PerfilBundle\Model\PerfilInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class NavegacionController extends Controller
{
    /**
     * @Route("/login-redirect", name="ad_perfil_login_redirect")
     * @Security("is_granted('ROLE_USER')")
     */
    public function loginRedirectAction(Request $request)
    {
        $user = $this->getUser();
        if (!$user) {
            return $this->redirectToRoute('fos_user_security_login');
        }

        $perfilId = $request->getSession()->get($this->getParameter('ad_perfil.session_name'));

        /** @var PerfilInterface $perfil */
        $perfil = $user->getPerfil($perfilId);
        if (!$perfil) {
            $this->addFlash('danger', 'Perfil inválido o no asignado.');
            return $this->redirectToRoute($this->getParameter('ad_perfil.route_redirect'));
        }

        $routeInit = $perfil->getRouteInit();
        if ($routeInit) {
            return $this->redirectToRoute($routeInit);
        }

        return $this->redirectToRoute('ad_perfil_menu');
    }

    /**
     * @param Menu|null $menu
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/index/{menu_slug}", name="ad_perfil_menu", defaults={"menu_slug" : null})
     * @ParamConverter("menu", class="ADPerfilBundle:Menu", options={"mapping" : {"menu_slug" : "slug" }})
     * @Security("is_granted('menu',menu)")
     */
    public function indexAction(Menu $menu = null) {
        $this->get('ad_perfil.menu_manager')->setMenuActual($menu);
        $menu_id=is_null($menu) ? null : $menu->getId();
        $menus=$this->get('ad_perfil.menu_manager')->getMenusByMenuId($menu_id);
        $canCreate=$this->isGranted('permiso','ad_perfil-menu-new');
        if(!$canCreate && 1==count($menus)){
            /** @var Menu $mn */
            $mn=$menus[0];
            if($mn->getRoute() != '') {
                return $this->redirectToRoute($mn->getRoute());
            }
            else {
                return $this->redirectToRoute('ad_perfil_menu',['menu_slug' => $mn->getSlug()]);
            }
        }
        return $this->render('@ADPerfilBundle/Navegacion/index.html.twig', [
            'menus' => $menus,
            'menuActual' => $menu,
            'title' => is_null($menu) ? $this->getParameter('ad_perfil.navegacion.homepage_name') : $menu->getTitulo(),
            'subtitle' => is_null($menu) ? '' : $menu->getSubtitulo(),
            'canEdit' => $this->isGranted('permiso','ad_perfil-menu-edit'),
            'canCreate' => $canCreate
        ]);
    }

    /**
     * @param Menu|null $menu
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function breadcrumbsAction(Menu $menu = null){
        $menu=is_null($menu) ? $this->get('ad_perfil.menu_manager')->getMenuActual() : $menu;
        return $this->render('@ADPerfilBundle/Navegacion/breadcrumbs.html.twig', [
            'menu' => $menu,
            'homepage_route' => $this->getParameter('ad_perfil.navegacion.homepage_route'),
            'homepage_name' => $this->getParameter('ad_perfil.navegacion.homepage_name')]);
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/mapa-sitio", name="ad_perfil_mapa_sitio")
     * @Security("is_granted('permiso','ad_perfil-mn-mapa-sitio')")
     */
    public function mapaSitioAction(Request $request) {
        // $menus=$this->get('ad_perfil.menu_manager')->getMenusByMenuId(null);
        $menus = $this->get('ad_perfil.menu_manager')->getFullMenuTree();

        $perfil=$this->get('ad_perfil.perfil_manager')->find($request->getSession()->get($this->getParameter('ad_perfil.session_name')));
        return $this->render('@ADPerfilBundle/Navegacion/mapa-sitio.html.twig',['menus' => $menus, 'perfil' => $perfil]);
    }

    /**
     * @param null $menu_id
     * @param bool $lateral Diferencia al menu desplegable principal de las secciones
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function menuAction($menu_id=null, $lateral=false) {
        $menu_id= $lateral===true ? null : $menu_id;
        $menus=$this->get('ad_perfil.menu_manager')->getMenusByMenuId($menu_id);
        return $this->render('@ADPerfilBundle/Navegacion/menu-'.(false===$lateral ? 'nav' : 'li').'.html.twig', [
            'menus' => $menus,
            'menuActual' => $this->get('ad_perfil.menu_manager')->getMenuActual()
        ]);
    }

    /**
     * Acción interna para renderizar el menú lateral extensible (icono + texto o solo icono).
     * Uso: {{ render(controller('ADPerfilBundle:Navegacion:menuLateral')) }}
     * @param bool $modoColapsado Controlado desde la vista por clase JS/CSS, no usado aquí directamente.
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function menuLateralAction()
    {
        $menus = $this->get('ad_perfil.menu_manager')->getFullMenuTree();

        return $this->render('@ADPerfilBundle/Navegacion/menu-lateral-extensible.html.twig', [
            'menus' => $menus,
            'menuActual' => $this->get('ad_perfil.menu_manager')->getMenuActual()
        ]);
    }



    /**
     * @param Request $request
     * @param Menu|null $menu
     * @param array|null $options
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function pageTitleAction(Request $request, Menu $menu = null, $options = array()){
        $options=array_merge($options,$request->attributes->all());
        $menu=is_null($menu) ? $this->get('ad_perfil.menu_manager')->getMenuActual() : $menu;
        $options=is_null($menu) ? [
            'icono' => isset($options['icono']) ? $options['icono'] : $this->getParameter('ad_perfil.navegacion.homepage_icono'),
            'color' => isset($options['color']) ? $options['color'] : $this->getParameter('ad_perfil.navegacion.homepage_color'),
            'title' => isset($options['title']) ? $options['title'] : $this->getParameter('ad_perfil.navegacion.homepage_title'),
            'subtitle' => isset($options['subtitle']) ? $options['subtitle'] : $this->getParameter('ad_perfil.navegacion.homepage_subtitle'),
        ] : [
            'icono' => isset($options['icono']) ? $options['icono'] : $menu->getIcono(),
            'color' => isset($options['color']) ? $options['color'] : $menu->getColor()->getNombre(),
            'title' => isset($options['title']) ? $options['title'] : $menu->getTitulo(),
            'subtitle' => isset($options['subtitle']) ? $options['subtitle'] : $menu->getSubtitulo()
        ];
        return $this->render('@ADPerfilBundle/Navegacion/page-title.html.twig', $options);
    }

    /**
     * @param null $menu_id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function submenuAction($menu_id=null) {
        $menus=$this->get('ad_perfil.menu_manager')->getSubmenusByMenuId($menu_id);
        return $this->render('@ADPerfilBundle/Navegacion/menu-nav-tab.html.twig', [
            'menus' => $menus,
            'menuActual' => $this->get('ad_perfil.menu_manager')->getMenuActual()
        ]);
    }

    /**
     * @param Request $request
     * @param Menu|null $menuSuperior
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @Route("/menu/new/{menu_slug}", name="ad_perfil_menu_new", defaults={"menu_slug" : null})
     * @ParamConverter("menuSuperior", class="ADPerfilBundle:Menu", options={"mapping" : {"menu_slug" : "slug" }})
     * @Security("is_granted('permiso','ad_perfil-menu-new')")
     */
    public function createAction(Request $request, Menu $menuSuperior = null){
        $menu=new Menu();
        $menu->setMenuSuperior($menuSuperior)
            ->setOrden($this->get('ad_perfil.menu_manager')->countItems($menuSuperior)+1);
        $form=$this->createForm(MenuFormType::class,$menu, ['super_admin' => true]);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($menu);
            $em->flush();
            $this->addFlash('success','Se creo correctamente el Menú '.$menu);
            return $this->redirectToRoute('ad_perfil_menu',[ 'menu_slug' => $this->get('ad_perfil.menu_manager')->getSlugActual()]);
        }
        return $this->render('@ADPerfilBundle/Navegacion/menu-new.html.twig', [
            'form' => $form->createView(),
            'menuSuperior' => $menuSuperior
        ]);
    }

    /**
     * @param Request $request
     * @param Menu|null $menu
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @Route("/menu/edit/{menu_slug}", name="ad_perfil_menu_edit", defaults={"menu_slug" : null})
     * @ParamConverter("menu", class="ADPerfilBundle:Menu", options={"mapping" : {"menu_slug" : "slug" }})
     * @Security("is_granted('permiso','ad_perfil-menu-edit')")
     */
    public function editAction(Request $request, Menu $menu) {
        if(is_null($menu)){
            $this->addFlash('danger','Debes haber seleccionado un menu para editar');
            return $this->redirectToRoute('ad_perfil_menu');
        }
        $form=$this->createForm(MenuFormType::class,$menu,['super_admin' => $this->isGranted('permiso','ad_perfil-menu-new')]);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($menu);
            $em->flush();

Resources/views/Navegacion/breadcrumb-item.html.twig
{% if menu is null %}
    <li class="breadcrumb-item"><a href="{{ path(homepage_route) }}">{{ homepage_name }}</a></li>
{% else %}
    {{ include('@ADPerfil/Navegacion/breadcrumb-item.html.twig',{ 'menu' :  menu.menuSuperior }) }}
    <li class="breadcrumb-item"><a href="{{ menu.route!='' ? path(menu.route) : path('ad_perfil_menu', {'menu_slug' : menu.slug}) }}">{{ menu.nombre | title }}</a></li>
{% endif %}

Resources/views/Navegacion/breadcrumbs.html.twig
{% if menu is not null %}
<ol class="breadcrumb">
    {{ include('@ADPerfilBundle/Navegacion/breadcrumb-item.html.twig',{ 'menu' :  menu.menuSuperior }) }}
    <li class="active">{{ menu.nombre | title }}</li>
</ol>
{% endif %}

Resources/views/Navegacion/index.html.twig
{% extends '@ADPerfilBundle/layout.html.twig' %}

{% block ad_perfil_title %}{{ title }}{% endblock ad_perfil_title %}

{% block ad_perfil_subtitle %}{{ subtitle }}{% endblock ad_perfil_subtitle %}

{% block ad_perfil_content %}
    {{ include('@ADPerfilBundle/Navegacion/index_content.html.twig') }}
{% endblock ad_perfil_content %}

Resources/views/Navegacion/mapa-sitio.html.twig
{% extends '@ADPerfilBundle/layout.html.twig' %}

{% block ad_perfil_title %}Mapa Del Sitio{% endblock ad_perfil_title %}
{% block ad_perfil_subtitle %}{{ perfil }}{% endblock ad_perfil_subtitle %}

{% block ad_perfil_content %}
    {{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::breadcrumbsAction')) }}
    {{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::menuAction')) }}
    {{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::pageTitleAction')) }}

    {{ include('@ADPerfilBundle/Navegacion/mapa-sitio_content.html.twig') }}
{% endblock ad_perfil_content %}

Resources/views/Navegacion/mapa-sitio_content.html.twig
<ul>
    {% for menu in menus if menu.visible and (menu.permiso is null or is_granted('permiso', menu.permiso.nombre)) %}
        <li {% if submenu is not defined %}class="col-md-6 col-sm-6 col-xs-12"{% endif %}>
            {% if menu.icono %}<i class="fa-fw {{ menu.icono }}"></i>&nbsp;{% endif %}
            <a href="{% if menu.route != '' %}{{ path(menu.route) }}{% else %}{{ path('ad_perfil_menu', {'menu_slug' : menu.slug}) }}{% endif %}">{{ menu.nombre | title }}</a>
            {% if menu.menuHijos | length %}
                {{ include('@ADPerfilBundle/Navegacion/mapa-sitio_content.html.twig',{'menus' : menu.menuHijos, 'submenu' : true}) }}
            {% endif %}
        </li>
    {% endfor %}
</ul>

Resources/views/Navegacion/menu-edit.html.twig
{% extends '@ADPerfilBundle/layout.html.twig' %}

{% block ad_perfil_title %}Editar Menu{% endblock ad_perfil_title %}
{% block ad_perfil_subtitle %}{{ menu }}{% endblock ad_perfil_subtitle %}

{% block ad_perfil_content %}
    {{ include('@ADPerfilBundle/Navegacion/menu-edit_content.html.twig') }}
{% endblock ad_perfil_content %}

Resources/views/Navegacion/menu-edit_content.html.twig
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::breadcrumbsAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::menuAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::pageTitleAction')) }}

<form method="post" class="form-horizontal">
    {{ form_widget(form) }}
    <button class="btn btn-primary" type="submit">Actualizar</button>
</form>

Resources/views/Navegacion/menu-lateral-extensible.html.twig
<aside class="adperfil-menu-lateral hidden-xs">
    <ul class="adperfil-menu-lateral list-group">
        <div class="adperfil-menu-lateral-header text-center">
            <button class="btn btn-default adperfil-toggle-menu" onclick="toggleMenuLateral()">
                <span class="adperfil-menu-icon-bars">
                    <span class="adperfil-icon-bar"></span>
                    <span class="adperfil-icon-bar"></span>
                    <span class="adperfil-icon-bar"></span>
                </span>
                <i class="glyphicon glyphicon-chevron-left"></i>
                <i class="glyphicon glyphicon-chevron-right" style="display:none;"></i>
            </button>
        </div>

        {% for menu in menus %}
            <li class="list-group-item {% if menu.isActual(menuActual) %}activo{% endif %}">
                <a href="{{ menu.route ? path(menu.route) : path('ad_perfil_menu', { 'menu_slug': menu.slug }) }}"
                   title="{{ menu.nombre }}">
                    <span class="adperfil-icono adperfil-icono-{{ menu.color|default('gris') | lower }}">
                        <i class="{{ menu.icono|default('fa fa-square') }}"></i>
                    </span>
                    <span class="adperfil-texto-menu">{{ menu.nombre }}</span>
                </a>
            </li>

            {% if menu.menuHijos|length > 0 %}
                <ul class="adperfil-submenu">
                    {% for submenu in menu.menuHijos %}
                        <li class="adperfil-submenu-item {% if submenu.isActual(menuActual) %}activo{% endif %}">
                            <a href="{{ submenu.route ? path(submenu.route) : path('ad_perfil_menu', { 'menu_slug': submenu.slug }) }}"
                               title="{{ submenu.nombre }}">
                                <span class="adperfil-icono adperfil-icono-{{ submenu.color|default('gris') | lower }}">
                                    <i class="{{ submenu.icono|default('fa fa-angle-right') }}"></i>
                                </span>
                                <span class="adperfil-texto-menu">{{ submenu.nombre }}</span>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endfor %}
    </ul>
</aside>
<script>
    function toggleMenuLateral() {
        var aside = document.querySelector('.adperfil-menu-lateral');
        aside.classList.toggle('colapsado');

        var left = aside.querySelector('.glyphicon-chevron-left');
        var right = aside.querySelector('.glyphicon-chevron-right');
        if (aside.classList.contains('colapsado')) {
            left.style.display = 'none';
            right.style.display = 'inline-block';
        } else {
            left.style.display = 'inline-block';
            right.style.display = 'none';
        }
    }
</script>

Resources/views/Navegacion/menu-li.html.twig
{% for menu in menus %}
    <li {% if menu.isActual(menuActual) %}class="active"{% endif %}>
        <a class="dropdown-item" href="{{ menu.route != '' ? path(menu.route) : path('ad_perfil_menu', { 'menu_slug' : menu.slug}) }}">
            <i class="{{ menu.icono!='' ? menu.icono : 'fa fa-square' }} fa-fw"></i> {{ menu.nombre | title | raw }}
        </a>
    </li>
{% endfor %}

Resources/views/Navegacion/menu-nav-tab.html.twig
{% if menus | length > 1 %}
<div class="row">
    <nav class="navbar navbar-default">
        <ul class="nav nav-tabs nav-justified">
            {{ include('@ADPerfilBundle/Navegacion/menu-li.html.twig') }}
        </ul>
    </nav>
</div>
{% endif %}

Resources/views/Navegacion/menu-nav.html.twig
{% if menus | length > 1 %}
<div class="row">
    <nav class="navbar navbar-default">
        <ul class="nav navbar-nav">
            {{ include('@ADPerfilBundle/Navegacion/menu-li.html.twig') }}
        </ul>
    </nav>
</div>
{% endif %}

Resources/views/Navegacion/menu-new.html.twig
{% extends '@ADPerfilBundle/layout.html.twig' %}

{% block ad_perfil_title %}Crear Menu{% endblock ad_perfil_title %}
{% block ad_perfil_subtitle %}{{ menuSuperior }}{% endblock ad_perfil_subtitle %}

{% block ad_perfil_content %}
    {{ include('@ADPerfilBundle/Navegacion/menu-new_content.html.twig') }}
{% endblock ad_perfil_content %}

Resources/views/Navegacion/menu-new_content.html.twig
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::breadcrumbsAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::menuAction')) }}
{{ render(controller('AscensoDigital\\PerfilBundle\\Controller\\NavegacionController::pageTitleAction')) }}

<form method="post" class="form-horizontal">
    {{ form_widget(form) }}
    <button class="btn btn-primary" type="submit">Crear</button>
</form>

Resources/views/Navegacion/menu.html.twig
{% for menu in menus %}
    <li>
        <a href="{{ menu.route != '' ? path(menu.route) : path('ad_perfil_menu', { 'menu_slug' : menu.slug}) }}">
            <i class="{{ menu.icono!='' ? menu.icono : 'fa fa-square' }} fa-fw"></i> {{ menu.nombre | title | raw }}
        </a>
    </li>
{% endfor %}